name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-12

    steps:
      - uses: actions/checkout@v2

      - name: Run build
        run: swift build

      - name: Run tests
        run: swift test
